[catalouge]
catalogue.shivv-aws.fun

[mongodb]
mongodb.shivv-aws.fun

[redis]
redis.shivv-aws.fun

[mysql]
mysql.shivv-aws.fun

[rabbitmq]
rabbitmq.shivv-aws.fun





[frontend]
172.31.47.172


[cart]
172.31.30.172 

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
; [local:vars]
; COURSE=ANSIBLE
; DURATION=10HRS
; TRAINER=SIVA KUMAR